-- 코드를 작성해주세요
SELECT ID, FISH_NAME , LENGTH FROM FISH_INFO F
    JOIN FISH_NAME_INFO FI ON F.FISH_TYPE = FI.FISH_TYPE
    WHERE (F.FISH_TYPE, F.LENGTH) IN (
        SELECT FISH_TYPE, MAX(LENGTH)
        FROM FISH_INFO 
        WHERE LENGTH IS NOT NULL
        GROUP BY FISH_TYPE
    )
    ORDER BY F.ID ASC
    